config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :locations do
    resources :characters
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
    @location = Location.find(params[:location_id])
    @character = @location.characters.new
    render :new
  end
  def create
  @location = Location.find(params[:location_id])
  @character = @location.characters.new(character_params)
  if @character.save
    redirect_to location_path(@location)
  else
    render :new
  end
end
def show
  @location = Location.find(params[:location_id])
  @character = Character.find(params[:id])
  render :show
end
def edit
  @location = Location.find(params[:location_id])
  @character = Character.find(params[:id])
  render :edit
end
def update
  @character = Character.find(params[:id])
  if @character.update(character_params)
    redirect_to location_path(@character.location)
  else
    render :edit
  end
end
def destroy
  @character = Character.find(params[:id])
  @character.destroy
  redirect_to location_path(@character.location)
end

# Other controller actions go here.

private
  def character_params
    params.require(:character).permit(:name, :lyrics)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
    render :index
  end

  def new
    @location = Location.new
    render :new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    render :edit
  end

  def show
    @location = Location.find(params[:id])
    render :show
  end

  def update
    @location= Location.find(params[:id])
    if @location.update(location_params)
      redirect_to locations_path
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end
  private
  def location_params
    params.require(:location).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/edit.html.erb
<h2>Create a Charater!</h2>
<%= form_for [@location, @character] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :items %>
  <%= f.text_field :items %>

  <%= f.submit  %>
<% end %>

app/views/characters/new.html.erb
<h2>Create a Charater!</h2>
<%= form_for [@location, @character] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :items %>
  <%= f.text_field :items %>

  <%= f.submit  %>
<% end %>

app/views/characters/show.html.erb
<h1>Character: <%= @character.name %></h1>
<h2>Location: <%= @location.name %></h2>

<p><%= link_to "Edit character", edit_location_character_path(@location, @character) %></p>
<p><%= link_to "Delete character", location_character_path(@location, @character),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to location", location_path(@location) %></p>

app/views/home/index.html.erb
<h1>Welcome!</h1>
<p><%= link_to "Locations", locations_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsRpg</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <p><%= link_to "Log out", destroy_user_session_path, :method => :delete %></p>
  <%= yield %>
</body>
</html>

app/views/locations/edit.html.erb
<h1>New Locations</h1>

<%= form_for @location do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<% if @locations.any? %>
  <ul>
    <% @locations.each do |location| %>
      <li><%= link_to location.name, location_path(location) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no locations yet.</p>
<% end %>


<p><%= link_to "Create new location", new_location_path %></p>

app/views/locations/new.html.erb
<h1>New Locations</h1>

<%= form_for @location do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>


<% if @location.characters.any? %>
  <h4>Here are the characters for this location:</h4>

  <% @location.characters.each do |character| %>
    <ul>
      <li>
        <%= link_to character.name, location_character_path(@location, character) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No characters are listed for this location.</p>
<% end %>

<p><%= link_to "Add a character", new_location_character_path(@location) %></p>

<p><%= link_to "Edit", edit_location_path(@location) %></p>
<p><%= link_to "Delete location", location_path(@location),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to locations", locations_path %></p>